import os
from pathlib import Path
from ultralytics import YOLO
from roboflow import Roboflow
from ultralytics import YOLO


HOME = os.getcwd()
print(HOME)

rf = Roboflow(api_key="KEY")
# pull dataset from roboflow, the code below are generated by roboflow website
project = rf.workspace("playground-7insr").project("tennis-court-detection-onesd-ipydn")
version = project.version(4)
dataset = version.download("yolov8")
data_yaml = str(Path(dataset.location) / "data.yaml")

model = YOLO("yolov8x-pose.pt")
model.train(
    data=data_yaml,
    epochs=200,
    batch=16,
    imgsz=640,
    workers=1,  # important for running on slurm
    plots=True,
    mosaic=0.0,
    val=True,
    fliplr=0.0,  # disable horizontal flip data augmentation
    # better results without flip augmentation, as we didin't play with flip idx, when frames are flipped, the keypoints
    # are mismatched with their idx, causing some of them to collapse to the bot left corner
    # during training.
)

# upload the trained model to Roboflow universe, load it from the universe when we want to use it
project.version(dataset.version).deploy(
    model_type="yolov8-pose", model_path=f"{HOME}/runs/pose/train/"
)
