import os
from pathlib import Path
from roboflow import Roboflow
from ultralytics import YOLO

HOME = os.getcwd()
print(HOME)

rf = Roboflow(api_key="KEY")
# pull dataset from roboflow, the code below are generated by roboflow website
project = rf.workspace("playground-7insr").project("tennis-match-cqbju")
version = project.version(3)
dataset = version.download("yolov8")
data_yaml = str(Path(dataset.location) / "data.yaml")

model = YOLO("yolov8x.pt")
model.train(
    data=data_yaml,
    epochs=75,
    batch=4,
    imgsz=1280,
    workers=1,  # important for slurm
    plots=True,
    val=True,
)

# upload the trained model to Roboflow universe, load it from the universe when we want to use it
project.version(dataset.version).deploy(
    model_type="yolov8", model_path=f"{HOME}/runs/detect/train/"
)
